linters-settings:
  govet:
    enable-all: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/davidschrooten/manifold-k8s

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

run:
  timeout: 5m
  go: '1.23'
  skip-dirs:
    - vendor
  skip-files:
    - ".*_test.go"

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
